import random

# Expanded list of conversation samples
conversation_samples = [
    "Hey, did you catch that new episode last night?",
    "Not yet! Is it good?",
    "Yeah, it's amazing. You should watch it asap!",
    "I need to find some time for it.",
    "Same here! Been super busy lately.",
    "I feel that, life just keeps getting in the way.",
    "I swear, every time I plan to relax, something comes up.",
    "Haha, story of my life. 😂",
    "By the way, have you seen the new update for the game?",
    "No, I haven’t had time. Is it a big one?",
    "Yeah, tons of new features. You’ll love it.",
    "I’ve been meaning to check it out. Maybe this weekend.",
    "Let me know when you’re online, we can play together!",
    "Sounds good, I’ll ping you.",
    "For sure! Catch you later!",
    "Take care!",
    "Anyone up for a voice chat later?",
    "What's everyone playing these days?",
    "Just finished a new game, it was really fun!",
    "How was your day?",
    "I’m so tired today, barely slept.",
    "Haha, I feel that. I’ve been working nonstop.",
    "What’s the plan for the weekend?",
    "I might catch up on some movies this weekend.",
    "Let’s do a movie night!",
    "I can't wait for the new movie to drop this Friday.",
    "I need a break, maybe take a walk.",
    "How’s everything with you?",
    "I’ve been meaning to ask, how’s your project going?",
    "Oh, it’s going great! I’m almost done.",
    "Nice, that’s awesome to hear!",
    "How’s work been? Anything exciting?",
    "Not much, just the usual grind.",
    "Did you see that crazy meme on Twitter?",
    "Yeah, it was hilarious. 😂",
    "I need to stop scrolling through memes, it’s addicting.",
    "What’s up? Long time no chat!",
    "I’ve been caught up with school, but I’m free now.",
    "Got any plans for today?",
    "Just chilling, not much going on.",
    "I’m thinking of trying out a new game tonight.",
    "What game? I’m always looking for new ones.",
    "It's called 'Valorant'. Ever tried it?",
    "Oh yeah, I’ve heard of it. It’s really popular.",
    "I’m getting back into League of Legends. Need some teammates!",
    "Let’s play together! I’m down for League.",
    "I’ll probably be busy this weekend, but maybe next week.",
    "You been on TikTok lately? Crazy stuff there.",
    "Yeah, TikTok’s full of crazy content. Some of it is hilarious!",
    "I’m obsessed with watching food recipes on TikTok.",
    "I just started watching that show you recommended. It's good!",
    "Glad you liked it! It gets better.",
    "I need to catch up on my shows too. So many episodes behind.",
    "You should try this new series I found. It’s really good.",
    "What did you have for lunch today?",
    "I had a burger. What about you?",
    "I made pasta today, it was delicious!",
    "Did you try that new coffee shop in the area?",
    "Not yet, but I’ve heard it’s great.",
    "I’m craving something sweet. Maybe I’ll get some donuts.",
    "Anyone want to join me for a game later?",
    "Let’s go for a run tomorrow morning!",
    "I can’t believe how fast this week is going.",
    "Time flies when you're busy, huh?",
    "I think I’m coming down with something, feeling off.",
    "Oh no, get some rest! Hope you feel better soon.",
    "I need to hit the gym today. Been slacking off.",
    "Same! I’ll go after work, hopefully.",
    "How do you feel about the new update on Discord?",
    "I love it! The interface looks amazing now.",
    "Yeah, the new features are pretty neat.",
    "Got any good book recommendations?",
    "I just finished a great one! Let me send you the name.",
    "I need to get back into reading. Been distracted by other things.",
    "How’s your family doing?",
    "They’re doing well, thanks for asking!",
    "How’s everything at home?",
    "It’s been good, just a bit busy lately.",
    "I’m so tired, been working overtime.",
    "I feel you, I’ve been working late too.",
    "How’s your cat doing?",
    "She’s great! Always getting into mischief.",
    "I’m considering getting a dog. Thoughts?",
    "Dogs are great! You should get one if you can.",
    "I’m still on the fence about it. It’s a big responsibility.",
    "What’s your favorite pizza topping?",
    "Definitely pepperoni. How about you?",
    "Mushrooms all the way. Best topping ever!",
    "I’m craving pizza right now, haha."
]

# Create a file and write 10,000 lines of conversation
with open('message_examples.txt', 'w') as f:
    for _ in range(10000):
        message = random.choice(conversation_samples)
        f.write(message + "\n")

print("message_examples.txt with 10,000 lines created.")